name: Singularity Build (docker)
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        singularity_version:
          - '3.5.3'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    steps:
    
    - name: Check out code for the container build
      uses: actions/checkout@v1

    - name: Set user token
      run: |
       mkdir .docker; touch .docker/config.json &&\
       echo "{"auths": {"docker.pkg.github.com": {"auth": "${{ secrets.DOCKER_SEC }}"}},"HttpHeaders": {"User-Agent": "Docker-Client"}}" >> .docker/config

    - name: Build Container
      env:
        SINGULARITY_RECIPE: singularity_container/debian_pycal_NO_JULIA.def
        OUTPUT_CONTAINER: container.sif
      run: |
       ls
       if [ -f "${SINGULARITY_RECIPE}" ]; then
           singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
       else
           echo "${SINGULARITY_RECIPE} is not found."
           echo "Present working directory: $PWD"
           ls
       fi
       
